### ISSUE TITLE
TODO List 

### ISSUE THREAD

**Issue by easyhooon** [TeamTripmate/tripmate-android#71]
- [x] README 작성 
- [x] 마이페이지 티켓 더미데이터가 들어가 있던 문제 해결
- [x] API 호출이 지연되는 화면 로딩 인디케이터 추가
- [x] 홈 화면 UI 디테일 보완(chil 리스트 양쪽 끝이 짤리는 문제, 리스트 최하단 패딩 추가, 상세 화면 뒤로가기 추가)
- [x] 텍스트 + 체크박스 컴포넌트의 경우 해당 전체 영역을 클릭 영역으로 확장 (ex) 동행찾기 탭 동행만 보기 체크박스)-> UX 개선
- [x] 동행 찾기 탭, 각 chip 을 눌렀을 때, chip 이 선택될 때 지연되는 문제 해결(API 호출 완료 후 칩이 선택되고 있음) -> 일단 loading animation 을 추가하는 것으로 쇼부
- [x] feature 모듈이 data 모듈을 의존하는 부분들 해결 
- [x] 온보딩 완료 API 추가되면 연동(온보딩이 종료되는 시점 변경, 결과 화면이 출력되면 온보딩이 종료되었다고 판단되어야 함)
- [ ] API 실패에 관한 처리(에러 다이얼로그 노출 및 재시도 로직)
- [x] 마이픽 기능 구현
- [ ] 여행 스타일 공유시 비트맵이 앱 내 파일로 저장되지 않도록 로직 수정 ~ing
- [x] 이미지 로드시 crossfade 애니메이션 적용 (현재 상세 화면 진입시 이미지가 깜빡거리는 문제가 존재)
- [x] 로딩 애니메이션 피그마와 같게 반영
- [ ] kotlin 2.0 migration
- [ ] type safe navigation 적용 + safe args
- [x] 내 여행 스타일 화면 statsubar 영역까지 확장 안되어있는 화면 확장해놓기(오픈 톡방 바로가기 화면)
- [ ] navigation argument viewModel 로 바로 전달 받는 방식으로 변경 (composable function 파라미터 제거, viewModel 내 uiState 로 바로 전달, 리컴포지션 최적화를 위함)

**Comment by easyhooon** [comment]
해야할 것 리스트 작성 부탁드려요~
완료 되었으면 체크하면 됩니다.

**Comment by kimdaeyou** [comment]
- [x] 홈 탭 카드뷰 여행지 카테고리 문구
- [x] 카테고리 확인 불가 시 팁 문구 디폴트 처리
- [x] 지도 뷰 전체 탭 마커 이미지 처리
- [x] 동행 신청하기 완료 토스트 추가

제가 선약이 있어서 목요일 저녘에나 추가 작업 할 수 있을꺼 같아요.
참고 부탁드려요

**Comment by kimdaeyou** [comment]
- [x] 내근처여행, 여행지 상세 화면 텍스트 테마 공통처리

**Comment by easyhooon** [comment]
- [ ] 내가 작성한 동행 모집글엔 내가 신청할 수 없도록 목록에 노출이 되면 안됨 -> 이 부분은 서버에 요청 필요(동행 신청 목록내에 내가 작성한 글은 필터링)
